stages:
  - test
  - build
  - release

.go_template:
  image: golang:latest

sast:
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml

format:
  extends: .go_template
  stage: test
  script:
    - make check/fmt

vet:
  extends: .go_template
  stage: test
  allow_failure: true
  script:
    - make vet

test:
  extends: .go_template
  stage: test
  script:
    - make test

build:
  extends: .go_template
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - grafana-matrix-forwarder
    expire_in: 1 day

build pages:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo:latest
  script:
    - apk add make
    - make docs/downloadTheme
    - make docs/build
  artifacts:
    paths:
      - _docs/public/

pages:
  stage: release
  image: alpine
  only:
    - main
  script:
    - mv _docs/public/ public/
  artifacts:
    paths:
      - public/

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
    GIT_DEPTH: 0
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  script: |
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/hctrdev/grafana-matrix-forwarder \
      -w /go/src/gitlab.com/hctrdev/grafana-matrix-forwarder \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      goreleaser/goreleaser release --clean
