project_name: grafana-matrix-forwarder
builds:
  - env: [CGO_ENABLED=0]
    binary: grafana-matrix-forwarder
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

dockers:
- image_templates:
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}-amd64"
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}.{{ .Minor }}-amd64"
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Version }}-amd64'
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:latest-amd64"
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://gitlab.com/hectorjsmith/grafana-matrix-forwarder
  - --label=org.opencontainers.image.source=https://gitlab.com/hectorjsmith/grafana-matrix-forwarder
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates:
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}-arm64"
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}.{{ .Minor }}-arm64"
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Version }}-arm64'
  - "registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:latest-arm64"
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://gitlab.com/hectorjsmith/grafana-matrix-forwarder
  - --label=org.opencontainers.image.source=https://gitlab.com/hectorjsmith/grafana-matrix-forwarder
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  goarch: arm64

docker_manifests:
- name_template: 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}.{{ .Minor }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Major }}.{{ .Minor }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Version }}'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Version }}-amd64'
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:{{ .Version }}-arm64'

- name_template: 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:latest'
  image_templates:
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:latest-amd64'
  - 'registry.gitlab.com/hectorjsmith/grafana-matrix-forwarder:latest-arm64'

changelog:
  groups:
    - title: "⛔ Breaking Changes"
      regexp: '^.*?!:.+$'
      order: 0
    - title: "🎉 Features"
      regexp: '^.*?feat(\(\w+\))??:.+$'
      order: 1
    - title: "🐛 Fixes"
      regexp: '^.*?fix(\(\w+\))??:.+$'
      order: 2
    - title: "📑 Other"
      order: 999
  filters:
    exclude:
      - "^Merge"
      - "^merge"
